name: CD

#dev브랜치가 push될 때 동작
on:
  push:
    branches: [ "develop" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      if: contains(github.ref, 'develop')
      run: SPRING_PROFILES_ACTIVE=[dev] ./gradlew clean build
      env:
        CLIENT_ID:  ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET:  ${{ secrets.CLIENT_SECRET }}
        DATABASE_URL:  ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME:  ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD:  ${{ secrets.DATABASE_PASSWORD }}
        JWT_SECRET_KEY:  ${{ secrets.JWT_SECRET_KEY }}
        MAIL_PASSWORD:  ${{ secrets.MAIL_PASSWORD }}

    - name: Deploy use SCP
      uses: appleboy/ssh-action@v0.1.10
      id: deploy-dev
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.NCP_DEV_SERVER_IP }}
        username: ${{ secrets.NCP_DEV_SERVER_USER }}
        password: ${{ secrets.NCP_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.NCP_DEV_SERVER_PORT }}
        source: "./build/libs/*-SNAPSHOT.jar"
        target: "~/deploy"

    - name: Execute Server Init Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_DEV_SERVER_IP }}
        username: ${{ secrets.NCP_DEV_SERVER_USER }}
        password: ${{ secrets.NCP_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.NCP_DEV_SERVER_PORT }}
        script_stop: true
        script: chmod +x ~/deploy/deploy.sh && sh ~/deploy/deploy.sh
