name: CD

#dev브랜치가 push될 때 동작
on:
  push:
    branches: [ "develop" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      if: contains(github.ref, 'develop')
      run: SPRING_PROFILES_ACTIVE=[dev] ./gradlew clean build

    - name: Deploy use SCP
      uses: appleboy/scp-action@master
      id: deploy-dev
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.NPC_DEV_SERVER_IP }}
        username: ${{ secrets.NPC_DEV_SERVER_USER }}
        password: ${{ secrets.NPC_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.NPC_DEV_SERVER_PORT }}
        source: "./build/libs/*.jar"
        target: "~/deploy"

    - name: Execute Server Init Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NPC_DEV_SERVER_IP }}
        username: ${{ secrets.NPC_DEV_SERVER_USER }}
        password: ${{ secrets.NPC_DEV_SERVER_PASSWORD }}
        port: ${{ secrets.NPC_DEV_SERVER_PORT }}
        script_stop: true
        script: chmod +x ~/deploy/deploy.sh && sh ~/deploy/deploy.sh
